[package]
name = "utils"
description = "protocol core utils packages"
version.workspace = true
cairo-version.workspace = true
edition.workspace = true

[lib]

[dependencies]
dojo.workspace = true
models = { path = "../models" }