[package]
name = "world"
description = "protocol core world contract"
version.workspace = true
cairo-version.workspace = true
edition.workspace = true


[lib]

[dependencies]
dojo.workspace = true
models = { path = "../models" }
utils = { path = "../utils" }
