[package]
name = "protocol_world"
description = "protocol core world contract"
cairo-version = "=2.7.0"
edition = "2024_07"
version = "0.1.0"


[[target.dojo]]
build-external-contracts = []

[dependencies]
protocol = { path = "../../core" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.12" }