[package]
name.workspace = true
version.workspace = true
description.workspace = true
cairo-version.workspace = true
edition.workspace = true

[cairo]
sierra-replace-ids = true

[lib]

[dependencies]
dojo.workspace = true
